heat_template_version: 2013-05-23

description: Beats ( Elasticsearch + Kibana ) Single CentOS 6

parameters:
  keypair_name:
    type: string
    label: keypair_name for all servers
    description: k5user keypair for all servers

  availability_zone:
    type: string
    label: availability_zone
    description: existing availability_zone

  dns_nameservers:
    type: comma_delimited_list
    description: dns name servers.
    default: ['133.162.193.9', '133.162.193.10']

  network_id:
    type: string
    label: Network ID
    description: existing network id

  subnet_id:
    type: string
    label: Subnet ID
    description: existing subnet id

  remote_host_cidr:
    type: string
    label: Host CIDR
    description: existing remote Host CIDR
    default: 0.0.0.0/0

  flavor:
    type: string
    label: Flavor
    default: S-1

resources:
  beats_single_c6:
    type: OS::Nova::Server
    properties:
      name: beats_single_c6
      key_name: { get_param: keypair_name }
      availability_zone: { get_param: availability_zone }
      block_device_mapping:
      - device_name: vda
        volume_id: {get_resource: beats_single_c6_systemvolume }
      flavor: { get_param: flavor }
      networks: [{"port": { get_resource: beats_single_c6_port }}]
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #cloud-config
            write_files:
            - path: /root/install.sh
              permissions: '0755'
              owner: root:root
              content: |
                #!/bin/bash

                echo -e '--Start Installing--\n\n'
                yum -y update

                cd /tmp
                wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u102-b14/jdk-8u102-linux-x64.rpm
                yum localinstall -y --nogpgcheck jdk-8u102-linux-x64.rpm

                echo -e '--Import GPG-KEY for Elasticsearch'
                rpm --import https://packages.elastic.co/GPG-KEY-elasticsearch

                echo -e '--Install Elasticsearch--\n'
                cat > /etc/yum.repos.d/elasticsearch.repo << 'EOS'
                [elasticsearch-2.x]
                name=Elasticsearch repository for 2.x packages
                baseurl=http://packages.elastic.co/elasticsearch/2.x/centos
                gpgcheck=1
                gpgkey=http://packages.elastic.co/GPG-KEY-elasticsearch
                enabled=1
                EOS
                yum -y install elasticsearch
                service elasticsearch restart
                chkconfig elasticsearch on

                echo -e '--Install Kibana--\n'
                cat > /etc/yum.repos.d/kibana.repo << 'EOS'
                [kibana-4.6]
                name=Kibana repository for 4.6.x packages
                baseurl=https://packages.elastic.co/kibana/4.6/centos
                gpgcheck=1
                gpgkey=https://packages.elastic.co/GPG-KEY-elasticsearch
                enabled=1
                EOS
                yum -y install kibana
                service kibana restart
                chkconfig kibana on

                echo -e '--Install Beats--\n'
                cat >> /etc/yum.repos.d/Beats.repo << 'EOS'
                [beats]
                name=Elastic Beats Repository
                baseurl=https://packages.elastic.co/beats/yum/el/$basearch
                enabled=1
                gpgkey=https://packages.elastic.co/GPG-KEY-elasticsearch
                gpgcheck=1
                EOS
                yum -y install topbeat
                yum -y install filebeat
                yum -y install packetbeat

                echo -e '--Install Beats Dashboard--\n'
                cd /tmp/
                curl -L -O http://download.elastic.co/beats/dashboards/beats-dashboards-1.3.0.zip
                unzip beats-dashboards-1.3.0.zip
                cd beats-dashboards-1.3.0/
                ./load.sh -url localhost:9200

                curl -XPUT 'http://localhost:9200/_template/packetbeat' -d@/etc/packetbeat/packetbeat.template.json
                service packetbeat start

                curl -XPUT 'http://localhost:9200/_template/topbeat' -d@/etc/topbeat/topbeat.template.json
                service topbeat start

                curl -XPUT 'http://localhost:9200/_template/filebeat' -d@/etc/filebeat/filebeat.template.json
                service filebeat start

                setsebool -P httpd_can_network_connect on

            runcmd:
              - cat /root/install.sh > /var/log/install.log
              - echo -e "\n-- installer log --\n" >> /var/log/install.log
              - /root/install.sh >> /var/log/install.log

          params:
            $beats_single_c6_IPADDR: { get_attr: [ beats_single_c6_port , fixed_ips, 0, ip_address ] }

  beats_single_c6_port:
    type: OS::Neutron::Port
    properties:
      name: beats_single_c6_port
      network_id: { get_param: network_id }
      availability_zone: { get_param: availability_zone }
      security_groups:
        - {get_resource: beats_single_c6_security_group }
      fixed_ips:
        - subnet_id: { get_param: subnet_id }

  beats_single_c6_systemvolume:
    type: OS::Cinder::Volume
    properties:
      availability_zone: { get_param: availability_zone }
      description:
      image: CentOS 6.5 64bit (English) 05
      name: beats_single_c6_systemvolume
      size: 30
      volume_type: M1

  beats_single_c6_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: beats_single_c6_security_group
      rules:
        # ICMP
        - { direction: ingress, ethertype: IPv4, protocol: icmp, remote_ip_prefix: { get_param: remote_host_cidr } }
        # SSH
        - { direction: ingress, ethertype: IPv4, port_range_min: 22, port_range_max: 22, protocol: tcp, remote_ip_prefix: { get_param: remote_host_cidr } }
        # HTTP
        - { direction: egress, ethertype: IPv4, port_range_min: 80, port_range_max: 80, protocol: tcp, remote_ip_prefix: 0.0.0.0/0 }
        # HTTPS
        - { direction: egress, ethertype: IPv4, port_range_min: 443, port_range_max: 443, protocol: tcp, remote_ip_prefix: 0.0.0.0/0 }
        # DNS
        - { direction: egress, ethertype: IPv4, port_range_min: 53, port_range_max: 53, protocol: tcp, remote_ip_prefix: { get_param: [dns_nameservers, 0] } }
        - { direction: egress, ethertype: IPv4, port_range_min: 53, port_range_max: 53, protocol: tcp, remote_ip_prefix: { get_param: [dns_nameservers, 1] } }
        - { direction: egress, ethertype: IPv4, port_range_min: 53, port_range_max: 53, protocol: udp, remote_ip_prefix: { get_param: [dns_nameservers, 0] } }
        - { direction: egress, ethertype: IPv4, port_range_min: 53, port_range_max: 53, protocol: udp, remote_ip_prefix: { get_param: [dns_nameservers, 1] } }
        # metadata
        - { direction: egress, port_range_max: 80, port_range_min: 80, protocol: tcp, remote_ip_prefix: 169.254.169.254/32 }

outputs:
  beats_single_c6_IP:
    value:
      str_replace:
        template: http://$ADDRESS/
        params:
          $ADDRESS: { get_attr: [ beats_single_c6_port, fixed_ips, 0, ip_address ] }
    description: beats_single_c6 IP Address
