heat_template_version: 2013-05-23

description: Drupal + Nginx Single CentOS 6

parameters:
  keypair_name:
    type: string
    label: keypair_name for all servers
    description: k5user keypair for all servers

  availability_zone:
    type: string
    label: availability_zone
    description: existing availability_zone

  dns_nameservers:
    type: comma_delimited_list
    description: dns name servers.
    default: ['133.162.193.9', '133.162.193.10']

  network_id:
    type: string
    label: Network ID
    description: existing network id

  subnet_id:
    type: string
    label: Subnet ID
    description: existing subnet id

  remote_host_cidr:
    type: string
    label: Host CIDR
    description: existing remote Host CIDR
    default: 0.0.0.0/0

  flavor:
    type: string
    label: Flavor
    default: S-1

resources:
  drupal_nginx_single_c6:
    type: OS::Nova::Server
    properties:
      name: drupal_nginx_single_c6
      key_name: { get_param: keypair_name }
      availability_zone: { get_param: availability_zone }
      block_device_mapping:
      - device_name: vda
        volume_id: {get_resource: drupal_nginx_single_c6_systemvolume }
      flavor: { get_param: flavor }
      networks: [{"port": { get_resource: drupal_nginx_single_c6_port }}]
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #cloud-config
            write_files:
            - path: /root/install.sh
              permissions: '0755'
              owner: root:root
              content: |
                #!/bin/bash
                echo -e '----Start installing VM----\n\n'
                yum -y update

                echo -e '--Install PHP 7.0.1--\n'
                yum -y install epel-release
                rpm -Uvh http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
                yum -y install --enablerepo=remi,remi-php70 php php-devel php-mbstring php-pdo php-mcrypt php-mysqlnd php-pecl-xdebug php-gd php-fpm php-opcache php-xml
                sed -i 's/^group = apache$/group = nginx/' /etc/php-fpm.d/www.conf
                sed -i 's/^user = apache$/user = nginx/' /etc/php-fpm.d/www.conf
                sed -i 's|^listen = 127\.0\.0\.1:9000$|listen = /var/run/php-fpm/php-fpm.sock|' /etc/php-fpm.d/www.conf
                sed -i 's|^;listen\.owner = nobody|listen.owner = nginx|' /etc/php-fpm.d/www.conf
                sed -i 's|^;listen\.group = nobody|listen.group = nginx|' /etc/php-fpm.d/www.conf

                echo -e '--Install MariaDB 10.1--\n'
                cat >> /etc/yum.repos.d/MariaDB.repo << 'EOS'
                [mariadb]
                name = MariaDB
                baseurl = http://yum.mariadb.org/10.1/centos6-amd64
                gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
                gpgcheck=1
                EOS

                yum -y install MariaDB-server MariaDB-devel MariaDB-common MariaDB-client
                cat >> /etc/my.cnf << 'EOS'

                [mysqld]
                character-set-server=utf8
                [client]
                default-character-set=utf8
                EOS

                sed -i 's|^pdo_mysql\.default_socket=$|pdo_mysql.default_socket = /var/lib/mysql/mysql.sock|' /etc/php.ini
                sed -i 's|^mysqli\.default_socket =$|mysqli.default_socket = /var/lib/mysql/mysql.sock|' /etc/php.ini
                echo 'mysql.default_socket = /var/lib/mysql/mysql.sock' >> /etc/php.ini
                service mysql start
                mysql -h localhost -u root -e "GRANT ALL PRIVILEGES ON *.* TO root@localhost IDENTIFIED BY 'drupal8_password';"
                mysql -h localhost -u root -pdrupal8_password -e "CREATE DATABASE d8;"
                mysql -h localhost -u root -pdrupal8_password -e "GRANT ALL PRIVILEGES ON d8.* TO 'drupal8'@'localhost' IDENTIFIED BY 'drupal8_password';"
                mysql -h localhost -u root -pdrupal8_password -e "GRANT ALL PRIVILEGES ON d8.* TO drupal8@\"%\" IDENTIFIED BY 'drupal8_password';"
                mysql -h localhost -u root -pdrupal8_password -e "GRANT ALL PRIVILEGES ON d8.* TO drupal8@localhost IDENTIFIED BY 'drupal8_password';"
                mysql -h localhost -u root -pdrupal8_password -e "GRANT ALL PRIVILEGES ON *.* TO root@\"%\" IDENTIFIED BY 'drupal8_password';"
                mysql -h localhost -u root -pdrupal8_password -e "DELETE FROM mysql.user WHERE User=''; DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1', '%'); DROP DATABASE test; DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'; FLUSH PRIVILEGES;"

                echo -e '--Install Nginx 1.10.1--\n'
                rpm -ivh http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
                yum -y install nginx
                cat > /etc/nginx/conf.d/default.conf << 'EOS'
                server {
                    listen       80;
                    server_name  localhost;
                    root /usr/share/nginx/drupal;
                    index index.php index.html index.htm;
                    location / {
                      try_files $uri $uri/ /index.php?q=$uri&$args;
                    }

                    error_page  404              /404.html;
                    error_page   500 502 503 504  /50x.html;
                    location = /50x.html {
                        root   /usr/share/nginx/html;
                    }

                    location ~ \.php$ {
                        root   /usr/share/nginx/drupal;
                        fastcgi_pass   unix:/var/run/php-fpm/php-fpm.sock;
                        fastcgi_index  index.php;
                        fastcgi_param  SCRIPT_FILENAME  $document_root/$fastcgi_script_name;
                        include        fastcgi_params;
                    }
                }
                EOS

                echo -e '--Install Drupal 8.1.8--\n'
                cd /usr/share/nginx/
                wget https://ftp.drupal.org/files/projects/drupal-8.1.8.tar.gz
                tar -xvzf drupal-8.1.8.tar.gz
                mkdir -p /usr/share/nginx/drupal-8.1.8/sites/default/files/translations
                wget https://ftp.drupal.org/files/translations/8.x/drupal/drupal-8.1.8.ja.po
                mv drupal-8.1.8.ja.po /usr/share/nginx/drupal-8.1.8/sites/default/files/translations
                #chmod ug+w /usr/share/nginx/drupal-8.1.8/sites/default/files/translations/drupal-8.1.8.ja.po
                chmod ug+w /usr/share/nginx/drupal-8.1.8/
                cp /usr/share/nginx/drupal-8.1.8/sites/default/default.settings.php /usr/share/nginx/drupal-8.1.8/sites/default/settings.php
                cp /usr/share/nginx/drupal-8.1.8/sites/default/default.services.yml /usr/share/nginx/drupal-8.1.8/sites/default/services.yml
                chmod ug+w /usr/share/nginx/drupal-8.1.8/sites/default/settings.php
                chmod ug+w /usr/share/nginx/drupal-8.1.8/sites/default/services.yml
                find /usr/share/nginx/drupal-8.1.8/sites/ -type d -exec chmod 777 {} +
                ln -s drupal-8.1.8 drupal
                chown -R nginx:nginx drupal-8.1.8 drupal
                chcon -R -t httpd_sys_content_rw_t /usr/share/nginx/drupal/sites/

                setsebool -P httpd_can_network_connect on

                service mysql restart
                chkconfig mysql on
                service php-fpm restart
                chkconfig php-fpm on
                service nginx restart
                chkconfig nginx on

            runcmd:
              - cat /root/install.sh > /var/log/install.log
              - echo -e "\n-- installer log --\n" >> /var/log/install.log
              - /root/install.sh 1>> /var/log/install.log 2>&1

          params:
            $drupal_nginx_single_c6_IPADDR: { get_attr: [ drupal_nginx_single_c6_port , fixed_ips, 0, ip_address ] }

  drupal_nginx_single_c6_port:
    type: OS::Neutron::Port
    properties:
      name: drupal_nginx_single_c6_port
      network_id: { get_param: network_id }
      availability_zone: { get_param: availability_zone }
      security_groups:
        - {get_resource: drupal_nginx_single_c6_common_security_group }
      fixed_ips:
        - subnet_id: { get_param: subnet_id }

  drupal_nginx_single_c6_systemvolume:
    type: OS::Cinder::Volume
    properties:
      availability_zone: { get_param: availability_zone }
      description:
      image: CentOS 6.5 64bit (English) 05
      name: drupal_nginx_single_c6_systemvolume
      size: 30
      volume_type: M1

  drupal_nginx_single_c6_common_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: drupal_nginx_single_c6_common_security_group
      rules:
        # ICMP
        - { direction: ingress, ethertype: IPv4, protocol: icmp, remote_ip_prefix: { get_param: remote_host_cidr } }
        # SSH
        - { direction: ingress, ethertype: IPv4, port_range_min: 22, port_range_max: 22, protocol: tcp, remote_ip_prefix: { get_param: remote_host_cidr } }
        # HTTP
        - { direction: egress, ethertype: IPv4, port_range_min: 80, port_range_max: 80, protocol: tcp, remote_ip_prefix: 0.0.0.0/0 }
        # HTTPS
        - { direction: egress, ethertype: IPv4, port_range_min: 443, port_range_max: 443, protocol: tcp, remote_ip_prefix: 0.0.0.0/0 }
        # DNS
        - { direction: egress, ethertype: IPv4, port_range_min: 53, port_range_max: 53, protocol: tcp, remote_ip_prefix: { get_param: [dns_nameservers, 0] } }
        - { direction: egress, ethertype: IPv4, port_range_min: 53, port_range_max: 53, protocol: tcp, remote_ip_prefix: { get_param: [dns_nameservers, 1] } }
        - { direction: egress, ethertype: IPv4, port_range_min: 53, port_range_max: 53, protocol: udp, remote_ip_prefix: { get_param: [dns_nameservers, 0] } }
        - { direction: egress, ethertype: IPv4, port_range_min: 53, port_range_max: 53, protocol: udp, remote_ip_prefix: { get_param: [dns_nameservers, 1] } }
        # metadata
        - { direction: egress, port_range_max: 80, port_range_min: 80, protocol: tcp, remote_ip_prefix: 169.254.169.254/32 }

outputs:
  drupal_nginx_single_c6_URL:
    value:
      str_replace:
        template: http://$ADDRESS/
        params:
          $ADDRESS: { get_attr: [ drupal_nginx_single_c6_port, fixed_ips, 0, ip_address ] }
    description: drupal_nginx_single_c6 URL
