heat_template_version: 2013-05-23

description: Openmeetings Single CentOS 6

parameters:
  keypair_name:
    type: string
    label: keypair_name for all servers
    description: k5user keypair for all servers

  availability_zone:
    type: string
    label: availability_zone
    description: existing availability_zone

  dns_nameservers:
    type: comma_delimited_list
    description: dns name servers.
    default: ['133.162.193.9', '133.162.193.10']

  network_id:
    type: string
    label: Network ID
    description: existing network id

  subnet_id:
    type: string
    label: Subnet ID
    description: existing subnet id

  remote_host_cidr:
    type: string
    label: Host CIDR
    description: existing remote Host CIDR
    default: 0.0.0.0/0

  flavor:
    type: string
    label: Flavor
    default: S-1

resources:
  openmeetings_single_c6:
    type: OS::Nova::Server
    properties:
      name: openmeetings_single_c6
      key_name: { get_param: keypair_name }
      availability_zone: { get_param: availability_zone }
      block_device_mapping:
      - device_name: vda
        volume_id: {get_resource: openmeetings_single_c6_systemvolume }
      flavor: { get_param: flavor }
      networks: [{"port": { get_resource: openmeetings_single_c6_port }}]
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #cloud-config
            write_files:
            - path: /root/install.sh
              permissions: '0755'
              owner: root:root
              content: |
                #!/bin/bash

                echo -e '----Start installing VM----\n\n'

                yum -y update
                yum -y install wget

                echo -e '--Install libraries--\n'
                yum -y groupinstall 'Development tools'

                echo -e '--Download and Install JDK 1.8.0--\n'
                cd /tmp/
                wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u102-b14/jdk-8u102-linux-x64.rpm
                yum localinstall -y --nogpgcheck jdk-8u102-linux-x64.rpm

                echo -e '--Install MySQL--\n'
                yum -y install mysql mysql-devel mysql-server mysql-utilities

                cat > /etc/my.cnf << 'EOS'
                [mysqld]
                datadir=/var/lib/mysql
                socket=/var/lib/mysql/mysql.sock
                user=mysql
                # Disabling symbolic-links is recommended to prevent assorted security risks
                symbolic-links=0
                default-character-set=utf8

                [mysqld_safe]
                log-error=/var/log/mysqld.log
                pid-file=/var/run/mysqld/mysqld.pid
                default-character-set=utf8

                [mysql]
                default-character-set=utf8
                EOS

                echo -e '--Install ImageMagick--\n'
                yum -y install ImageMagick

                echo -e '--Install GhostScript--\n'
                yum -y install ghostscript

                echo -e '--Download and Install SWFTools 0.9.2--\n'
                cd /tmp/
                yum -y install zlib-devel libjpeg-devel giflib-devel freetype-devel
                wget http://www.swftools.org/swftools-0.9.2.tar.gz
                tar -xzf swftools-0.9.2.tar.gz
                cd swftools-0.9.2
                ./configure
                make
                sed -i "s|-o -L.*||" /tmp/swftools-0.9.2/swfs/Makefile
                make install

                echo -e '--Download and Install LibreOffice 5.1.5--\n'
                cd /tmp/
                wget http://download.documentfoundation.org/libreoffice/stable/5.1.5/rpm/x86_64/LibreOffice_5.1.5_Linux_x86-64_rpm.tar.gz
                wget http://download.documentfoundation.org/libreoffice/stable/5.1.5/rpm/x86_64/LibreOffice_5.1.5_Linux_x86-64_rpm_langpack_ja.tar.gz
                wget http://download.documentfoundation.org/libreoffice/stable/5.1.5/rpm/x86_64/LibreOffice_5.1.5_Linux_x86-64_rpm_helppack_ja.tar.gz
                tar -xzf LibreOffice_5.1.5_Linux_x86-64_rpm.tar.gz
                tar -xzf LibreOffice_5.1.5_Linux_x86-64_rpm_langpack_ja.tar.gz
                tar -xzf LibreOffice_5.1.5_Linux_x86-64_rpm_helppack_ja.tar.gz
                cd /tmp/LibreOffice_5.1.5.2_Linux_x86-64_rpm/RPMS/
                yum -y localinstall --nogpgcheck lib*
                cd /tmp/LibreOffice_5.1.5.2_Linux_x86-64_rpm_langpack_ja/RPMS/
                yum -y localinstall --nogpgcheck lib*
                cd /tmp/LibreOffice_5.1.5.2_Linux_x86-64_rpm_helppack_ja/RPMS/
                yum -y localinstall --nogpgcheck lib*

                wget https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/jodconverter/jodconverter-core-3.0-beta-4-dist.zip
                unzip jodconverter-core-3.0-beta-4-dist.zip
                mv jodconverter-core-3.0-beta-4 /usr/lib

                echo -e '--Download and Install LAME 3.99.5--\n'
                cd /tmp/
                wget http://sourceforge.net/projects/lame/files/lame/3.99/lame-3.99.5.tar.gz
                tar -xzf lame-3.99.5.tar.gz
                cd lame-3.99.5
                ./configure
                make
                make install

                echo -e '--Download and Install FFmpeg 3.1.4--\n'
                cd /tmp/
                wget http://ffmpeg.org/releases/ffmpeg-3.1.4.tar.bz2
                tar xf ffmpeg-3.1.4.tar.bz2
                cd ffmpeg-3.1.4
                ./configure --enable-libmp3lame --disable-yasm
                make
                make install

                echo -e '--Install Sox--\n'
                yum -y install sox

                echo -e '--Download and Install Openmeetings 3.1.3--\n'
                mkdir /usr/local/openmeetings
                cd  /usr/local/openmeetings
                wget http://ftp.jaist.ac.jp/pub/apache/openmeetings/3.1.3/bin/apache-openmeetings-3.1.3.tar.gz
                tar -xzf apache-openmeetings-3.1.3.tar.gz
                cd ../

                cat > /etc/rc.d/init.d/openmeetings << 'EOS'
                #! /bin/sh
                # chkconfig: 345 95 90

                . /etc/rc.d/init.d/functions

                NAME=openmeetings
                RED5_DIR=/usr/local/$NAME
                START_DAEMON=$RED5_DIR/red5.sh
                STOP_DAEMON=$RED5_DIR/red5-shutdown.sh

                RUN_USER=$NAME

                PIDFILE=/var/run/$NAME.pid
                LOGFILE=/var/log/$NAME.log

                test -x $START_DAEMON || exit 5

                start() {
                    echo -n "Starting OpenMeetings Service:"
                    cd $RED5_DIR
                    su -s /bin/bash -c "$START_DAEMON &" $RUN_USER >> $LOGFILE 2>&1
                    RETVAL=$?
                    echo
                    [ $RETVAL = 0 ] && touch ${PIDFILE}
                    sleep 2
                    return $RETVAL
                }

                stop() {
                    echo -n "Shutting down OpenMeetings:"
                    cd $RED5_DIR
                    su -s /bin/bash -c "$STOP_DAEMON &" $RUN_USER >> $LOGFILE 2>&1
                    RETVAL=$?
                    echo
                    [ $RETVAL = 0 ] && rm -f ${PIDFILE}
                    sleep 2
                    return $RETVAL
                }

                case "$1" in
                    start)
                        start
                        ;;
                    stop)
                        stop
                        ;;
                    restart)
                        stop
                        start
                        ;;
                esac
                EOS

                chmod 755 /etc/rc.d/init.d/openmeetings

                sed -i 's|0\.0\.0\.0|$openmeetings_single_c6_IPADDR|' /usr/local/openmeetings/conf/red5.properties
                sed -i 's|localhost|$openmeetings_single_c6_IPADDR|' /usr/local/openmeetings/conf/red5.properties

                mv /usr/local/openmeetings/webapps/openmeetings/WEB-INF/classes/META-INF/persistence.xml /usr/local/openmeetings/webapps/openmeetings/WEB-INF/classes/META-INF/persistence.xml_ORG
                cp /usr/local/openmeetings/webapps/openmeetings/WEB-INF/classes/META-INF/mysql_persistence.xml /usr/local/openmeetings/webapps/openmeetings/WEB-INF/classes/META-INF/persistence.xml

                echo -e '--Download and Install ConnectoyJ 5.1.40--\n'
                cd /tmp/
                wget http://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-5.1.40.tar.gz
                tar xfz mysql-connector-java-5.1.40.tar.gz
                mv /tmp/mysql-connector-java-5.1.40/mysql-connector-java-5.1.40-bin.jar /usr/local/openmeetings/webapps/openmeetings/WEB-INF/lib/

                echo -e '--Start service Openmeetings and MySQL--\n'
                useradd openmeetings
                chown -R openmeetings:openmeetings /usr/local/openmeetings/

                service mysqld start
                chkconfig mysqld on
                service openmeetings start
                chkconfig openmeetings on


            runcmd:
              - cat /root/install.sh > /var/log/install.log
              - echo -e "\n-- installer log --\n" >> /var/log/install.log
              - /root/install.sh >> /var/log/install.log

          params:
            $openmeetings_single_c6_IPADDR: { get_attr: [ openmeetings_single_c6_port , fixed_ips, 0, ip_address ] }

  openmeetings_single_c6_port:
    type: OS::Neutron::Port
    properties:
      name: openmeetings_single_c6_port
      network_id: { get_param: network_id }
      availability_zone: { get_param: availability_zone }
      security_groups:
        - {get_resource: openmeetings_single_c6_security_group }
      fixed_ips:
        - subnet_id: { get_param: subnet_id }

  openmeetings_single_c6_systemvolume:
    type: OS::Cinder::Volume
    properties:
      availability_zone: { get_param: availability_zone }
      description:
      image: CentOS 6.5 64bit (English) 05
      name: openmeetings_single_c6_systemvolume
      size: 30
      volume_type: M1

  openmeetings_single_c6_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: openmeetings_single_c6_security_group
      rules:
        # ICMP
        - { direction: ingress, ethertype: IPv4, protocol: icmp, remote_ip_prefix: { get_param: remote_host_cidr } }
        # SSH
        - { direction: ingress, ethertype: IPv4, port_range_min: 22, port_range_max: 22, protocol: tcp, remote_ip_prefix: { get_param: remote_host_cidr } }
        # HTTP
        - { direction: egress, ethertype: IPv4, port_range_min: 80, port_range_max: 80, protocol: tcp, remote_ip_prefix: 0.0.0.0/0 }
        # HTTPS
        - { direction: egress, ethertype: IPv4, port_range_min: 443, port_range_max: 443, protocol: tcp, remote_ip_prefix: 0.0.0.0/0 }
        # DNS
        - { direction: egress, ethertype: IPv4, port_range_min: 53, port_range_max: 53, protocol: tcp, remote_ip_prefix: { get_param: [dns_nameservers, 0] } }
        - { direction: egress, ethertype: IPv4, port_range_min: 53, port_range_max: 53, protocol: tcp, remote_ip_prefix: { get_param: [dns_nameservers, 1] } }
        - { direction: egress, ethertype: IPv4, port_range_min: 53, port_range_max: 53, protocol: udp, remote_ip_prefix: { get_param: [dns_nameservers, 0] } }
        - { direction: egress, ethertype: IPv4, port_range_min: 53, port_range_max: 53, protocol: udp, remote_ip_prefix: { get_param: [dns_nameservers, 1] } }
        # metadata
        - { direction: egress, port_range_max: 80, port_range_min: 80, protocol: tcp, remote_ip_prefix: 169.254.169.254/32 }
        # http&rtmp
        - { direction: ingress, ethertype: IPv4, port_range_min: 5080, port_range_max: 5080, protocol: tcp, remote_ip_prefix: 0.0.0.0/0 }
        - { direction: egress,  ethertype: IPv4, port_range_min: 5080, port_range_max: 5080, protocol: tcp, remote_ip_prefix: 0.0.0.0/0 }
        #- { direction: ingress, ethertype: IPv4, port_range_min: 1935, port_range_max: 1935, protocol: tcp, remote_ip_prefix: 0.0.0.0/0 }
        #- { direction: egress,  ethertype: IPv4, port_range_min: 1935, port_range_max: 1935, protocol: tcp, remote_ip_prefix: 0.0.0.0/0 }

outputs:
  openmeetings_single_c6_IP:
    value:
      str_replace:
        template: http://$ADDRESS/
        params:
          $ADDRESS: { get_attr: [ openmeetings_single_c6_port, fixed_ips, 0, ip_address ] }
    description: openmeetings_single_c6 IP Address
