heat_template_version: 2013-05-23

description: SugarCRM-CE ( Apache ) Single CentOS 6

parameters:
  keypair_name:
    type: string
    label: keypair_name for all servers
    description: k5user keypair for all servers

  availability_zone:
    type: string
    label: availability_zone
    description: existing availability_zone

  dns_nameservers:
    type: comma_delimited_list
    description: dns name servers.
    default: ['133.162.193.9', '133.162.193.10']

  network_id:
    type: string
    label: Network ID
    description: existing network id

  subnet_id:
    type: string
    label: Subnet ID
    description: existing subnet id

  remote_host_cidr:
    type: string
    label: Host CIDR
    description: existing remote Host CIDR
    default: 0.0.0.0/0

  flavor:
    type: string
    label: Flavor
    default: S-1

resources:
  sugarcrm_ce_single_c6:
    type: OS::Nova::Server
    properties:
      name: sugarcrm_ce_single_c6
      key_name: { get_param: keypair_name }
      availability_zone: { get_param: availability_zone }
      block_device_mapping:
      - device_name: vda
        volume_id: {get_resource: sugarcrm_ce_single_c6_systemvolume }
      flavor: { get_param: flavor }
      networks: [{"port": { get_resource: sugarcrm_ce_single_c6_port }}]
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #cloud-config
            write_files:
            - path: /root/install.sh
              permissions: '0755'
              owner: root:root
              content: |
                #!/bin/bash
                echo -e '----Start installing VM----\n\n'

                echo -e '--Update system--\n'
                yum -y update

                echo -e '--Install wget--\n'
                yum -y install wget

                echo -e '--Install PHP 7.0.1--\n'
                yum -y install epel-release
                rpm -Uvh http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
                yum -y install --enablerepo=remi,remi-php70 php php-devel php-mbstring php-pdo php-mcrypt php-mysqlnd php-pecl-xdebug php-gd php-fpm php-opcache php-xml php-imap php-mysql php-mysqli php-zip
                sed -i 's|^upload_max_filesize = 2M$|upload_max_filesize = 20M|' /etc/php.ini
                sed -i 's|^listen = 127\.0\.0\.1:9000$|listen = /var/run/php-fpm/php-fpm.sock|' /etc/php-fpm.d/www.conf
                sed -i 's|^;listen\.owner = nobody|listen.owner = apache|' /etc/php-fpm.d/www.conf
                sed -i 's|^;listen\.group = nobody|listen.group = apache|' /etc/php-fpm.d/www.conf

                cat >> /etc/php.ini << 'EOS'

                mbstring.language = Japanese
                mbstring.internal_encoding = UTF-8
                mbstring.http_input = auto
                mbstring.http_output = pass
                mbstring.detect_order = auto
                mbstring.substitute_character = none
                EOS

                echo -e '--Install MariaDB 10.1--\n'
                cat >> /etc/yum.repos.d/MariaDB.repo << 'EOS'
                [mariadb]
                name = MariaDB
                baseurl = http://yum.mariadb.org/10.1/centos6-amd64
                gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
                gpgcheck=1
                EOS

                yum -y install MariaDB-server MariaDB-devel MariaDB-common MariaDB-client
                cat >> /etc/my.cnf << 'EOS'

                [mysqld]
                character-set-server=utf8
                [client]
                default-character-set=utf8
                EOS

                sed -i 's|^pdo_mysql\.default_socket=$|pdo_mysql.default_socket = /var/lib/mysql/mysql.sock|' /etc/php.ini
                sed -i 's|^mysqli\.default_socket =$|mysqli.default_socket = /var/lib/mysql/mysql.sock|' /etc/php.ini
                echo 'mysql.default_socket = /var/lib/mysql/mysql.sock' >> /etc/php.ini
                service mysql start
                mysql -h localhost -u root -e "GRANT ALL PRIVILEGES ON *.* TO root@localhost IDENTIFIED BY 'rootroot';"
                mysql -h localhost -u root -prootroot -e "CREATE DATABASE s6;"
                mysql -h localhost -u root -prootroot -e "GRANT ALL PRIVILEGES ON s6.* TO 'sugarce6'@'localhost' IDENTIFIED BY 'sugarce6_password';"
                mysql -h localhost -u root -prootroot -e "GRANT ALL PRIVILEGES ON s6.* TO sugarce6@\"%\" IDENTIFIED BY 'sugarce6_password';"
                mysql -h localhost -u root -prootroot -e "GRANT ALL PRIVILEGES ON s6.* TO sugarce6@localhost IDENTIFIED BY 'sugarce6_password';"
                mysql -h localhost -u root -prootroot -e "GRANT ALL PRIVILEGES ON *.* TO root@\"%\" IDENTIFIED BY 'rootroot';"
                mysql -h localhost -u root -prootroot -e "DELETE FROM mysql.user WHERE User=''; DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1', '%'); DROP DATABASE test; DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'; FLUSH PRIVILEGES;"

                echo -e '--Install Apache--\n'
                yum -y install httpd
                sed -i '/^#ServerName www\.example\.com:80$/a ServerName *:80' /etc/httpd/conf/httpd.conf
                sed -i 's|AllowOverride None|AllowOverride All|g' /etc/httpd/conf/httpd.conf
                sed -i 's|^DocumentRoot "/var/www/html"|DocumentRoot "/var/www/html/sugarce"|' /etc/httpd/conf/httpd.conf

                echo -e '--Install SugarCE 6.5.24--\n'
                cd /var/www/html
                wget https://sourceforge.net/projects/sugarcrm/files/1%20-%20SugarCRM%206.5.X/SugarCommunityEdition-6.5.X/SugarCE-6.5.24.zip
                unzip -q SugarCE-6.5.24.zip
                ln -s SugarCE-Full-6.5.24 sugarce
                chown -R apache:apache SugarCE-Full-6.5.24 sugarce
                chcon -R -t httpd_sys_content_rw_t /var/www/html

                setsebool -P httpd_can_network_connect on

                service mysql restart
                chkconfig mysql on
                service httpd start
                chkconfig httpd on

            runcmd:
              - cat /root/install.sh > /var/log/install.log
              - echo -e "\n-- installer log --\n" >> /var/log/install.log
              - /root/install.sh >> /var/log/install.log

          params:
            $sugarcrm_ce_single_c6_IPADDR: { get_attr: [ sugarcrm_ce_single_c6_port , fixed_ips, 0, ip_address ] }

  sugarcrm_ce_single_c6_port:
    type: OS::Neutron::Port
    properties:
      name: sugarcrm_ce_single_c6_port
      network_id: { get_param: network_id }
      availability_zone: { get_param: availability_zone }
      security_groups:
        - {get_resource: sugarcrm_ce_single_c6_common_security_group }
      fixed_ips:
        - subnet_id: { get_param: subnet_id }

  sugarcrm_ce_single_c6_systemvolume:
    type: OS::Cinder::Volume
    properties:
      availability_zone: { get_param: availability_zone }
      description:
      image: CentOS 6.5 64bit (English) 05
      name: sugarcrm_ce_single_c6_systemvolume
      size: 30
      volume_type: M1

  sugarcrm_ce_single_c6_common_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: sugarcrm_ce_single_c6_common_security_group
      rules:
        # ICMP
        - { direction: ingress, ethertype: IPv4, protocol: icmp, remote_ip_prefix: { get_param: remote_host_cidr } }
        # SSH
        - { direction: ingress, ethertype: IPv4, port_range_min: 22, port_range_max: 22, protocol: tcp, remote_ip_prefix: { get_param: remote_host_cidr } }
        # HTTP
        - { direction: egress, ethertype: IPv4, port_range_min: 80, port_range_max: 80, protocol: tcp, remote_ip_prefix: 0.0.0.0/0 }
        # HTTPS
        - { direction: egress, ethertype: IPv4, port_range_min: 443, port_range_max: 443, protocol: tcp, remote_ip_prefix: 0.0.0.0/0 }
        # DNS
        - { direction: egress, ethertype: IPv4, port_range_min: 53, port_range_max: 53, protocol: tcp, remote_ip_prefix: { get_param: [dns_nameservers, 0] } }
        - { direction: egress, ethertype: IPv4, port_range_min: 53, port_range_max: 53, protocol: tcp, remote_ip_prefix: { get_param: [dns_nameservers, 1] } }
        - { direction: egress, ethertype: IPv4, port_range_min: 53, port_range_max: 53, protocol: udp, remote_ip_prefix: { get_param: [dns_nameservers, 0] } }
        - { direction: egress, ethertype: IPv4, port_range_min: 53, port_range_max: 53, protocol: udp, remote_ip_prefix: { get_param: [dns_nameservers, 1] } }
        # metadata
        - { direction: egress, port_range_max: 80, port_range_min: 80, protocol: tcp, remote_ip_prefix: 169.254.169.254/32 }

outputs:
  sugarcrm_ce_single_c6_IP:
    value:
      str_replace:
        template: http://$ADDRESS/
        params:
          $ADDRESS: { get_attr: [ sugarcrm_ce_single_c6_port, fixed_ips, 0, ip_address ] }
    description: sugarcrm_ce_single_c6 IP Address
