heat_template_version: 2013-05-23

description: Nginx + Node.js Single CentOS 6

parameters:

  keypair_name:
    type: string
    label: keypair_name for all servers
    description: k5user keypair for all servers

  availability_zone:
    type: string
    label: availability_zone
    description: existing availability_zone

  dns_nameservers:
    type: comma_delimited_list
    description: dns name servers.
    default: ['133.162.193.9', '133.162.193.10']

  network_id:
    type: string
    label: Network ID
    description: existing network id

  subnet_id:
    type: string
    label: Subnet ID
    description: existing subnet id

  remote_host_cidr:
    type: string
    label: Host CIDR
    description: existing remote Host CIDR
    default: 0.0.0.0/0

  flavor:
    type: string
    label: Flavor
    default: S-1

resources:

  nginx_nodejs_single_c6:
    type: OS::Nova::Server
    properties:
      name: nginx_nodejs_single_c6
      key_name: { get_param: keypair_name }
      availability_zone: { get_param: availability_zone }
      block_device_mapping:
      - device_name: vda
        volume_id: {get_resource: nginx_nodejs_single_c6_systemvolume }
      flavor: { get_param: flavor }
      networks: [{"port": { get_resource: nginx_nodejs_single_c6_port }}]
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #cloud-config
            write_files:
            - path: /root/install.sh
              permissions: '0755'
              owner: root:root
              content: |
                #!/bin/bash
                echo -e '----Start installing VM----\n\n'

                echo -e '\n--Update system--'
                yum -y update

                echo -e '\n--Install wget--'
                yum -y install wget

                echo -e '\n--Install nginx--'
                rpm -ivh http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
                yum -y install nginx

                echo -e '\n--Modify /etc/nginx/conf.d/default.conf--'
                sed -i '/^server {$/i upstream backend_node {\n    ip_hash;\n    server 127\.0\.0\.1:3000;\n}\n'  /etc/nginx/conf.d/default.conf
                sed -i '/^        index  index.html index.htm;$/a \\n        if ( -f $request_filename ) {\n            break;\n        }\n\n        if ( !-f $request_filename ) {\n            proxy_pass http://backend_node;\n            break;\n        }\n' /etc/nginx/conf.d/default.conf

                echo -e '\n--Cat /etc/nginx/conf.d/default.conf--'
                cat /etc/nginx/conf.d/default.conf

                echo -e '\n--Install node.js--'
                curl --silent --location https://rpm.nodesource.com/setup_4.x | bash -
                yum -y install nodejs

                echo -e '\n--Create node.js http server--'
                cat >> /usr/etc/node-http.js << 'EOS'
                var http = require('http');

                http.createServer(function (req, res) {

                    res.writeHead(200, {'Content-Type': 'text/plain'});
                    res.end('node.js works at 3000\n');

                }).listen(3000, '127.0.0.1');
                EOS

                echo -e '\n--Set SELinux boolean httpd_can_network_connect to on--'
                setsebool -P httpd_can_network_connect 1

                echo -e '\n--Service start nginx and node.js--'
                node /usr/etc/node-http.js &

                service nginx start
                chkconfig nginx on

            runcmd:
              - cat /root/install.sh > /var/log/install.log
              - echo -e "\n-- installer log --\n" >> /var/log/install.log
              - /root/install.sh >> /var/log/install.log

          params:
            $nginx_nodejs_single_c6_IPADDR: { get_attr: [ nginx_nodejs_single_c6_port , fixed_ips,0, ip_address ] }

  nginx_nodejs_single_c6_port:
    type: OS::Neutron::Port
    properties:
      name: nginx_nodejs_single_c6_port
      network_id: { get_param: network_id }
      availability_zone: { get_param: availability_zone }
      security_groups:
        - {get_resource: nginx_nodejs_single_c6_common_security_group }
      fixed_ips:
        - subnet_id: { get_param: subnet_id }

  nginx_nodejs_single_c6_systemvolume:
    type: OS::Cinder::Volume
    properties:
      availability_zone: { get_param: availability_zone }
      description:
      image: CentOS 6.5 64bit (English) 05
      name: nginx_nodejs_single_c6_systemvolume
      size: 30
      volume_type: M1

  nginx_nodejs_single_c6_common_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: nginx_nodejs_single_c6_common_security_group
      rules:
        # ICMP
        - { direction: ingress, ethertype: IPv4, protocol: icmp, remote_ip_prefix: { get_param: remote_host_cidr } }
        # SSH
        - { direction: ingress, ethertype: IPv4, port_range_min: 22, port_range_max: 22, protocol: tcp, remote_ip_prefix: { get_param: remote_host_cidr } }
        # HTTP
        - { direction: egress, ethertype: IPv4, port_range_min: 80, port_range_max: 80, protocol: tcp, remote_ip_prefix: 0.0.0.0/0 }
        # HTTPS
        - { direction: egress, ethertype: IPv4, port_range_min: 443, port_range_max: 443, protocol: tcp, remote_ip_prefix: 0.0.0.0/0 }
        # DNS
        - { direction: egress, ethertype: IPv4, port_range_min: 53, port_range_max: 53, protocol: tcp, remote_ip_prefix: { get_param: [dns_nameservers, 0] } }
        - { direction: egress, ethertype: IPv4, port_range_min: 53, port_range_max: 53, protocol: tcp, remote_ip_prefix: { get_param: [dns_nameservers, 1] } }
        - { direction: egress, ethertype: IPv4, port_range_min: 53, port_range_max: 53, protocol: udp, remote_ip_prefix: { get_param: [dns_nameservers, 0] } }
        - { direction: egress, ethertype: IPv4, port_range_min: 53, port_range_max: 53, protocol: udp, remote_ip_prefix: { get_param: [dns_nameservers, 1] } }
        # metadata
        - { direction: egress, port_range_max: 80, port_range_min: 80, protocol: tcp, remote_ip_prefix: 169.254.169.254/32 }


outputs:
  nginx_nodejs_single_c6_IP:
    value:
      str_replace:
        template: http://$ADDRESS/
        params:
          $ADDRESS: { get_attr: [ nginx_nodejs_single_c6_port, fixed_ips, 0, ip_address ] }
    description: nginx_nodejs_single_c6 IP Address
